const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY={tasks:'devboard.tasks.v2',notes:'devboard.notes.v2',activity:'devboard.activity.v2',theme:'devboard.theme',muted:'devboard.muted'};
let tasks=JSON.parse(localStorage.getItem(KEY.tasks)||'[]');
let activity=JSON.parse(localStorage.getItem(KEY.activity)||'{}');
let muted=localStorage.getItem(KEY.muted)==='true';
const tips=['Small quests become big wins.','Ship something small today.','Debugging is just detective work.','Consistency beats intensity.','Every commit is another evolution.','Train the skill you want to master.'];
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2500)}
function dateNow(){const n=new Date();$('#currentDate').textContent=n.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('#timezone').textContent=Intl.DateTimeFormat().resolvedOptions().timeZone.replace('_',' ');$('#footerYear').textContent=n.getFullYear()}
function clock(){const n=new Date();let h=n.getHours();const p=h>=12?'PM':'AM';h=h%12||12;$('#clock').textContent=`${String(h).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}:${String(n.getSeconds()).padStart(2,'0')} ${p}`}
function dayKey(d=new Date()){return d.toISOString().slice(0,10)}
function calcStreak(){let streak=0,d=new Date();while(activity[dayKey(d)]>0){streak++;d.setDate(d.getDate()-1)}return streak}
function renderTasks(){const list=$('#taskList'),empty=$('#taskEmpty');list.innerHTML='';tasks.forEach((t,i)=>{const el=document.createElement('div');el.className='task'+(t.done?' completed':'');el.innerHTML=`<input type="checkbox" ${t.done?'checked':''} aria-label="Complete task"><span>${esc(t.text)}</span><button class="delete-task" data-i="${i}" aria-label="Delete task">×</button>`;list.appendChild(el)});empty.style.display=tasks.length?'none':'block';updateStats();}
function updateStats(){const total=tasks.length,done=tasks.filter(t=>t.done).length,rate=total?Math.round(done/total*100):0,streak=calcStreak();$('#totalTasks').textContent=total;$('#completedTasks').textContent=done;$('#completionRate').textContent=rate+'%';$('#streak').textContent=streak;$('#heroStreak').textContent=`${streak} day${streak===1?'':'s'}`;$('#activityTotal').textContent=Object.values(activity).reduce((a,b)=>a+b,0);const vals=Object.values(activity);$('#activityBest').textContent=`Best: ${vals.length?Math.max(...vals):0}/day`;const active=vals.filter(v=>v>0).length;$('#activeDays').textContent=`${active} active day${active===1?'':'s'}`;const xp=Math.min(500,260+done*10),pct=Math.round(xp/500*100);$('#xpValue').textContent=xp;$('#heroXp').textContent=xp;$('#xpPercent').textContent=pct+'%';$('#trainerProgress').style.width=pct+'%';$('#heroProgress').style.width=pct+'%';$('#powerPercent').textContent=pct+'%';$('#powerRing').style.background=`conic-gradient(var(--yellow) 0 ${pct}%,#1a304b ${pct}% 100%)`;$('#powerLevel').textContent=pct>=90?'Elite Trainer':pct>=70?'Advanced Trainer':pct>=50?'Rising Trainer':'New Trainer';const milestone=done===0?['First Quest','Complete a task to unlock your first badge.']:done<5?['Quest Hunter',`${5-done} more completed quest${5-done===1?'':'s'} to unlock.`]:done<10?['Combo Master',`${10-done} more completed quests to unlock.`]:['Evolution Ready','You have completed 10+ quests. Keep going!'];$('#milestoneText').textContent=milestone[0];$('#milestoneSub').textContent=milestone[1]}
function addTask(){const input=$('#taskInput'),text=input.value.trim();if(!text)return;tasks.unshift({text,done:false,created:Date.now()});save(KEY.tasks,tasks);input.value='';renderTasks();toast('Quest added · +10 XP ⚡');input.focus()}
$('#addTask').onclick=addTask;$('#taskInput').addEventListener('keydown',e=>{if(e.key==='Enter')addTask()});$('#taskList').addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;const item=e.target.closest('.task'),i=[...$('#taskList').children].indexOf(item);if(i<0)return;tasks[i].done=e.target.checked;if(e.target.checked){const k=dayKey();activity[k]=(activity[k]||0)+1;save(KEY.activity,activity);toast('Quest completed · +10 XP 🎉')}else toast('Quest reopened');save(KEY.tasks,tasks);renderTasks();renderHeatmap()});$('#taskList').addEventListener('click',e=>{if(!e.target.classList.contains('delete-task'))return;tasks.splice(Number(e.target.dataset.i),1);save(KEY.tasks,tasks);renderTasks();toast('Quest removed')});$('#clearDone').onclick=()=>{tasks=tasks.filter(t=>!t.done);save(KEY.tasks,tasks);renderTasks();toast('Completed quests cleared')};
const notes=$('#notes');notes.value=localStorage.getItem(KEY.notes)||'';function updateWords(){const n=notes.value.trim();$('#wordCount').textContent=(n?n.split(/\s+/).length:0)+' words'}updateWords();notes.addEventListener('input',()=>{localStorage.setItem(KEY.notes,notes.value);$('#saveStatus').textContent='● Saving...';$('#saveStatus').classList.add('saving');clearTimeout(window.__save);window.__save=setTimeout(()=>{$('#saveStatus').textContent='● Saved';$('#saveStatus').classList.remove('saving')},450);updateWords()});
function renderHeatmap(){const h=$('#heatmap');h.innerHTML='';const end=new Date(),days=[];for(let i=83;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);days.push(dayKey(d))}days.forEach(k=>{const c=document.createElement('div'),v=activity[k]||0;c.className='heatmap-cell '+(v>=4?'level4':v===3?'level3':v===2?'level2':v===1?'level1':'');c.title=`${v} completed quest${v===1?'':'s'} · ${k}`;h.appendChild(c)})}
function setTheme(){const light=localStorage.getItem(KEY.theme)==='light';document.body.classList.toggle('light',light);$('#themeBtn').textContent=light?'🌙':'☀️'}$('#themeBtn').onclick=()=>{const light=!document.body.classList.contains('light');localStorage.setItem(KEY.theme,light?'light':'dark');setTheme();toast(light?'Light mode enabled ☀️':'Dark mode enabled 🌙')};function setMute(){muted=localStorage.getItem(KEY.muted)==='true';$('#muteBtn').textContent=muted?'🔇':'🔊'}$('#muteBtn').onclick=()=>{muted=!muted;localStorage.setItem(KEY.muted,muted);setMute();toast(muted?'Sound muted 🔇':'Sound enabled 🔊')};
const modal=$('#modal'),modalContent=$('#modalContent');function openModal(html){modalContent.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}modal.addEventListener('click',e=>{if(e.target.dataset.close!==undefined)closeModal()});
function achievements(){const done=tasks.filter(t=>t.done).length,streak=calcStreak(),items=[['⚡','First Quest','Complete your first quest',done>=1],['🎯','Quest Hunter','Complete 5 quests',done>=5],['🔥','On Fire','Reach a 7 day streak',streak>=7],['💻','Code Trainer','Complete 10 quests',done>=10],['🏆','Evolution','Reach 25 completed quests',done>=25],['✦','Legend','Reach 30 active coding days',Object.values(activity).filter(v=>v>0).length>=30]];openModal(`<div class="modal-title">🏆 Achievements</div><div class="modal-sub">Your badges evolve as you use the dashboard.</div><div class="achievement-grid">${items.map(x=>`<div class="achievement ${x[3]?'':'locked'}"><b>${x[0]} ${x[1]}</b><span>${x[2]}</span><small>${x[3]?'UNLOCKED':'LOCKED'}</small></div>`).join('')}</div>`)}
function settings(){openModal(`<div class="modal-title">⚙ Settings</div><div class="modal-sub">Personalize your trainer dashboard. Data stays in this browser.</div><div class="settings-grid"><div class="setting-row"><div><strong>Appearance</strong><span>Switch between dark and light mode.</span></div><button class="toggle ${document.body.classList.contains('light')?'on':''}" data-setting="theme"></button></div><div class="setting-row"><div><strong>Sound</strong><span>Enable or mute dashboard feedback.</span></div><button class="toggle ${!muted?'on':''}" data-setting="sound"></button></div><div class="setting-row"><div><strong>Clear completed</strong><span>Remove finished quests only.</span></div><button class="outline-btn" data-setting="done">Clear</button></div><div class="setting-row"><div><strong>Reset dashboard</strong><span>Delete tasks, notes and activity.</span></div><button class="outline-btn" data-setting="reset">Reset</button></div></div>`);modalContent.querySelectorAll('[data-setting]').forEach(b=>b.onclick=()=>{const a=b.dataset.setting;if(a==='theme'){$('#themeBtn').click();settings()}if(a==='sound'){$('#muteBtn').click();settings()}if(a==='done'){$('#clearDone').click();settings()}if(a==='reset'){if(confirm('Reset all local DevBoard data?')){localStorage.removeItem(KEY.tasks);localStorage.removeItem(KEY.notes);localStorage.removeItem(KEY.activity);tasks=[];activity={};notes.value='';renderTasks();renderHeatmap();updateWords();updateStats();toast('Dashboard reset');settings()}}})}
function profile(){openModal(`<div class="profile-modal"><div class="profile-big">NK</div><div class="modal-title">Code Trainer</div><div class="modal-sub">Level 5 · Pokémon Developer</div><div class="setting-row"><div><strong>Quest completion</strong><span>${tasks.filter(t=>t.done).length} completed out of ${tasks.length}</span></div><strong style="color:var(--yellow)">${$('#completionRate').textContent}</strong></div><br><div class="setting-row"><div><strong>Current streak</strong><span>Keep completing quests daily.</span></div><strong style="color:var(--orange)">${calcStreak()} days</strong></div></div>`)}
$$('.nav-item').forEach(btn=>btn.onclick=()=>navigate(btn.dataset.section));function navigate(section){const labels={dashboard:'Dashboard',tasks:'Tasks',notes:'Notes',activity:'Activity',projects:'Projects'};$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===section));$('#pageName').textContent=labels[section]||section[0].toUpperCase()+section.slice(1);if(labels[section]){$(`[data-section-panel="${section}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});return}if(section==='achievements')achievements();if(section==='settings')settings()};$('#profileBtn').onclick=profile;$('#shareBtn').onclick=async()=>{const data={title:'DevBoard ⚡',text:'Check out my Pokémon developer dashboard!'};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('Dashboard link copied ↗')}}catch{} };$$('[data-open="achievements"]').forEach(b=>b.onclick=achievements);$('#addProject').onclick=()=>openModal(`<div class="modal-title">✨ New Project</div><div class="modal-sub">Your next Pokédex entry starts here.</div><div class="setting-row"><div><strong>Project slot ready</strong><span>Add a real project URL and details when you are ready to publish.</span></div><button class="outline-btn" data-close>Got it</button></div>`);
$$('.project-link').forEach(b=>b.onclick=()=>{const p=b.closest('.project'),name=p.dataset.project;openModal(`<div class="modal-title">${name}</div><div class="modal-sub">Pokédex project profile</div><div class="setting-row"><div><strong>Development status</strong><span>Ready for your GitHub/live URL.</span></div><strong style="color:var(--green)">ACTIVE</strong></div><br><div class="setting-row"><div><strong>Stack</strong><span>${[...p.querySelectorAll('.tags span')].map(x=>x.textContent).join(' · ')}</span></div></div>`)});
const palette=$('#commandPalette'),input=$('#commandInput'),results=$('#commandResults');const commands=[['⌂','Dashboard','dashboard'],['✓','Tasks','tasks'],['▤','Notes','notes'],['◫','Activity','activity'],['◇','Projects','projects'],['♛','Achievements','achievements'],['⚙','Settings','settings']];function renderCommands(q=''){results.innerHTML=commands.filter(x=>x[1].toLowerCase().includes(q.toLowerCase())).map(x=>`<div class="command-result" data-command="${x[2]}"><b>${x[0]} ${x[1]}</b><span>Open</span></div>`).join('')||'<div class="command-result"><span>No results</span></div>';$$('.command-result[data-command]').forEach(r=>r.onclick=()=>{palette.classList.remove('open');navigate(r.dataset.command)})}$('#searchBtn').onclick=()=>{palette.classList.add('open');input.value='';renderCommands();setTimeout(()=>input.focus(),30)};input.addEventListener('input',()=>renderCommands(input.value));palette.addEventListener('click',e=>{if(e.target.dataset.closeSearch!==undefined)palette.classList.remove('open')});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchBtn').click()}if(e.key==='Escape'){palette.classList.remove('open');closeModal()}});
$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$$('.nav-item').forEach(b=>b.addEventListener('click',()=>$('#sidebar').classList.remove('open')));
$('#tipText').textContent=tips[new Date().getDate()%tips.length];setTheme();setMute();dateNow();clock();renderTasks();renderHeatmap();updateStats();setInterval(clock,1000);setInterval(dateNow,60000);