const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY={tasks:'devboard.tasks.v2',notes:'devboard.notes.v2',activity:'devboard.activity.v2',theme:'devboard.theme',muted:'devboard.muted'};
let tasks=JSON.parse(localStorage.getItem(KEY.tasks)||'[]');
let activity=JSON.parse(localStorage.getItem(KEY.activity)||'{}');
let muted=localStorage.getItem(KEY.muted)==='true';
const tips=['Small quests become big wins.','Ship something small today.','Debugging is just detective work.','Consistency beats intensity.','Every commit is another evolution.','Train the skill you want to master.'];
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2500)}
function dateNow(){const n=new Date();$('#currentDate').textContent=n.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('#timezone').textContent=Intl.DateTimeFormat().resolvedOptions().timeZone.replace('_',' ');$('#footerYear').textContent=n.getFullYear()}
function clock(){const n=new Date();let h=n.getHours();const p=h>=12?'PM':'AM';h=h%12||12;$('#clock').textContent=`${String(h).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}:${String(n.getSeconds()).padStart(2,'0')} ${p}`}
function dayKey(d=new Date()){return d.toISOString().slice(0,10)}
function calcStreak(){let streak=0,d=new Date();while(activity[dayKey(d)]>0){streak++;d.setDate(d.getDate()-1)}return streak}
function renderTasks(){const list=$('#taskList'),empty=$('#taskEmpty');list.innerHTML='';tasks.forEach((t,i)=>{const el=document.createElement('div');el.className='task'+(t.done?' completed':'');el.innerHTML=`<input type="checkbox" ${t.done?'checked':''} aria-label="Complete task"><span>${esc(t.text)}</span><button class="delete-task" data-i="${i}" aria-label="Delete task">×</button>`;list.appendChild(el)});empty.style.display=tasks.length?'none':'block';updateStats();}
function updateStats(){const total=tasks.length,done=tasks.filter(t=>t.done).length,rate=total?Math.round(done/total*100):0,streak=calcStreak();$('#totalTasks').textContent=total;$('#completedTasks').textContent=done;$('#completionRate').textContent=rate+'%';$('#streak').textContent=streak;$('#heroStreak').textContent=`${streak} day${streak===1?'':'s'}`;$('#activityTotal').textContent=Object.values(activity).reduce((a,b)=>a+b,0);const vals=Object.values(activity);$('#activityBest').textContent=`Best: ${vals.length?Math.max(...vals):0}/day`;const active=vals.filter(v=>v>0).length;$('#activeDays').textContent=`${active} active day${active===1?'':'s'}`;const xp=Math.min(500,260+done*10),pct=Math.round(xp/500*100);$('#xpValue').textContent=xp;$('#heroXp').textContent=xp;$('#xpPercent').textContent=pct+'%';$('#trainerProgress').style.width=pct+'%';$('#heroProgress').style.width=pct+'%';$('#powerPercent').textContent=pct+'%';$('#powerRing').style.background=`conic-gradient(var(--yellow) 0 ${pct}%,#1a304b ${pct}% 100%)`;$('#powerLevel').textContent=pct>=90?'Elite Trainer':pct>=70?'Advanced Trainer':pct>=50?'Rising Trainer':'New Trainer';const milestone=done===0?['First Quest','Complete a task to unlock your first badge.']:done<5?['Quest Hunter',`${5-done} more completed quest${5-done===1?'':'s'} to unlock.`]:done<10?['Combo Master',`${10-done} more completed quests to unlock.`]:['Evolution Ready','You have completed 10+ quests. Keep going!'];$('#milestoneText').textContent=milestone[0];$('#milestoneSub').textContent=milestone[1]}
function addTask(){const input=$('#taskInput'),text=input.value.trim();if(!text)return;tasks.unshift({text,done:false,created:Date.now()});save(KEY.tasks,tasks);input.value='';renderTasks();toast('Quest added · +10 XP ⚡');input.focus()}
$('#addTask').onclick=addTask;$('#taskInput').addEventListener('keydown',e=>{if(e.key==='Enter')addTask()});$('#taskList').addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;const item=e.target.closest('.task'),i=[...$('#taskList').children].indexOf(item);if(i<0)return;tasks[i].done=e.target.checked;if(e.target.checked){const k=dayKey();activity[k]=(activity[k]||0)+1;save(KEY.activity,activity);toast('Quest completed · +10 XP 🎉')}else toast('Quest reopened');save(KEY.tasks,tasks);renderTasks();renderHeatmap()});$('#taskList').addEventListener('click',e=>{if(!e.target.classList.contains('delete-task'))return;tasks.splice(Number(e.target.dataset.i),1);save(KEY.tasks,tasks);renderTasks();toast('Quest removed')});$('#clearDone').onclick=()=>{tasks=tasks.filter(t=>!t.done);save(KEY.tasks,tasks);renderTasks();toast('Completed quests cleared')};
const notes=$('#notes');notes.value=localStorage.getItem(KEY.notes)||'';function updateWords(){const n=notes.value.trim();$('#wordCount').textContent=(n?n.split(/\s+/).length:0)+' words'}updateWords();notes.addEventListener('input',()=>{localStorage.setItem(KEY.notes,notes.value);$('#saveStatus').textContent='● Saving...';$('#saveStatus').classList.add('saving');clearTimeout(window.__save);window.__save=setTimeout(()=>{$('#saveStatus').textContent='● Saved';$('#saveStatus').classList.remove('saving')},450);updateWords()});
function renderHeatmap(){const h=$('#heatmap');h.innerHTML='';const end=new Date(),days=[];for(let i=83;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);days.push(dayKey(d))}days.forEach(k=>{const c=document.createElement('div'),v=activity[k]||0;c.className='heatmap-cell '+(v>=4?'level4':v===3?'level3':v===2?'level2':v===1?'level1':'');c.title=`${v} completed quest${v===1?'':'s'} · ${k}`;h.appendChild(c)})}
function setTheme(){const light=localStorage.getItem(KEY.theme)==='light';document.body.classList.toggle('light',light);$('#themeBtn').textContent=light?'🌙':'☀️'}$('#themeBtn').onclick=()=>{const light=!document.body.classList.contains('light');localStorage.setItem(KEY.theme,light?'light':'dark');setTheme();toast(light?'Light mode enabled ☀️':'Dark mode enabled 🌙')};function setMute(){muted=localStorage.getItem(KEY.muted)==='true';$('#muteBtn').textContent=muted?'🔇':'🔊'}$('#muteBtn').onclick=()=>{muted=!muted;localStorage.setItem(KEY.muted,muted);setMute();toast(muted?'Sound muted 🔇':'Sound enabled 🔊')};
const modal=$('#modal'),modalContent=$('#modalContent');function openModal(html){modalContent.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}modal.addEventListener('click',e=>{if(e.target.dataset.close!==undefined)closeModal()});
function achievements(){const done=tasks.filter(t=>t.done).length,streak=calcStreak(),items=[['⚡','First Quest','Complete your first quest',done>=1],['🎯','Quest Hunter','Complete 5 quests',done>=5],['🔥','On Fire','Reach a 7 day streak',streak>=7],['💻','Code Trainer','Complete 10 quests',done>=10],['🏆','Evolution','Reach 25 completed quests',done>=25],['✦','Legend','Reach 30 active coding days',Object.values(activity).filter(v=>v>0).length>=30]];openModal(`<div class="modal-title">🏆 Achievements</div><div class="modal-sub">Your badges evolve as you use the dashboard.</div><div class="achievement-grid">${items.map(x=>`<div class="achievement ${x[3]?'':'locked'}"><b>${x[0]} ${x[1]}</b><span>${x[2]}</span><small>${x[3]?'UNLOCKED':'LOCKED'}</small></div>`).join('')}</div>`)}
function settings(){openModal(`<div class="modal-title">⚙ Settings</div><div class="modal-sub">Personalize your trainer dashboard. Data stays in this browser.</div><div class="settings-grid"><div class="setting-row"><div><strong>Appearance</strong><span>Switch between dark and light mode.</span></div><button class="toggle ${document.body.classList.contains('light')?'on':''}" data-setting="theme"></button></div><div class="setting-row"><div><strong>Sound</strong><span>Enable or mute dashboard feedback.</span></div><button class="toggle ${!muted?'on':''}" data-setting="sound"></button></div><div class="setting-row"><div><strong>Clear completed</strong><span>Remove finished quests only.</span></div><button class="outline-btn" data-setting="done">Clear</button></div><div class="setting-row"><div><strong>Reset dashboard</strong><span>Delete tasks, notes and activity.</span></div><button class="outline-btn" data-setting="reset">Reset</button></div></div>`);modalContent.querySelectorAll('[data-setting]').forEach(b=>b.onclick=()=>{const a=b.dataset.setting;if(a==='theme'){$('#themeBtn').click();settings()}if(a==='sound'){$('#muteBtn').click();settings()}if(a==='done'){$('#clearDone').click();settings()}if(a==='reset'){if(confirm('Reset all local DevBoard data?')){localStorage.removeItem(KEY.tasks);localStorage.removeItem(KEY.notes);localStorage.removeItem(KEY.activity);tasks=[];activity={};notes.value='';renderTasks();renderHeatmap();updateWords();updateStats();toast('Dashboard reset');settings()}}})}
function profile(){openModal(`<div class="profile-modal"><div class="profile-big">NK</div><div class="modal-title">Code Trainer</div><div class="modal-sub">Level 5 · Pokémon Developer</div><div class="setting-row"><div><strong>Quest completion</strong><span>${tasks.filter(t=>t.done).length} completed out of ${tasks.length}</span></div><strong style="color:var(--yellow)">${$('#completionRate').textContent}</strong></div><br><div class="setting-row"><div><strong>Current streak</strong><span>Keep completing quests daily.</span></div><strong style="color:var(--orange)">${calcStreak()} days</strong></div></div>`)}
$$('.nav-item').forEach(btn=>btn.onclick=()=>navigate(btn.dataset.section));function navigate(section){const labels={dashboard:'Dashboard',tasks:'Tasks',notes:'Notes',activity:'Activity',projects:'Projects'};$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===section));$('#pageName').textContent=labels[section]||section[0].toUpperCase()+section.slice(1);if(labels[section]){$(`[data-section-panel="${section}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});return}if(section==='achievements')achievements();if(section==='settings')settings()};$('#profileBtn').onclick=profile;$('#shareBtn').onclick=async()=>{const data={title:'DevBoard ⚡',text:'Check out my Pokémon developer dashboard!'};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('Dashboard link copied ↗')}}catch{} };$$('[data-open="achievements"]').forEach(b=>b.onclick=achievements);$('#addProject').onclick=()=>openModal(`<div class="modal-title">✨ New Project</div><div class="modal-sub">Your next Pokédex entry starts here.</div><div class="setting-row"><div><strong>Project slot ready</strong><span>Add a real project URL and details when you are ready to publish.</span></div><button class="outline-btn" data-close>Got it</button></div>`);
$$('.project-link').forEach(b=>b.onclick=()=>{const p=b.closest('.project'),name=p.dataset.project;openModal(`<div class="modal-title">${name}</div><div class="modal-sub">Pokédex project profile</div><div class="setting-row"><div><strong>Development status</strong><span>Ready for your GitHub/live URL.</span></div><strong style="color:var(--green)">ACTIVE</strong></div><br><div class="setting-row"><div><strong>Stack</strong><span>${[...p.querySelectorAll('.tags span')].map(x=>x.textContent).join(' · ')}</span></div></div>`)});
const palette=$('#commandPalette'),input=$('#commandInput'),results=$('#commandResults');const commands=[['⌂','Dashboard','dashboard'],['✓','Tasks','tasks'],['▤','Notes','notes'],['◫','Activity','activity'],['◇','Projects','projects'],['♛','Achievements','achievements'],['⚙','Settings','settings']];function renderCommands(q=''){results.innerHTML=commands.filter(x=>x[1].toLowerCase().includes(q.toLowerCase())).map(x=>`<div class="command-result" data-command="${x[2]}"><b>${x[0]} ${x[1]}</b><span>Open</span></div>`).join('')||'<div class="command-result"><span>No results</span></div>';$$('.command-result[data-command]').forEach(r=>r.onclick=()=>{palette.classList.remove('open');navigate(r.dataset.command)})}$('#searchBtn').onclick=()=>{palette.classList.add('open');input.value='';renderCommands();setTimeout(()=>input.focus(),30)};input.addEventListener('input',()=>renderCommands(input.value));palette.addEventListener('click',e=>{if(e.target.dataset.closeSearch!==undefined)palette.classList.remove('open')});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchBtn').click()}if(e.key==='Escape'){palette.classList.remove('open');closeModal()}});
$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$$('.nav-item').forEach(b=>b.addEventListener('click',()=>$('#sidebar').classList.remove('open')));
$('#tipText').textContent=tips[new Date().getDate()%tips.length];setTheme();setMute();dateNow();clock();renderTasks();renderHeatmap();updateStats();setInterval(clock,1000);setInterval(dateNow,60000);

/* ================= ADVANCED QUEST MANAGER ================= */
(function(){
  const taskInput=$('#taskInput'), oldAdd=$('#addTask'), oldList=$('#taskList'), oldClear=$('#clearDone');
  if(!taskInput||!oldAdd||!oldList)return;
  tasks=tasks.map((t,i)=>({id:t.id||`q_${t.created||Date.now()}_${i}`,text:t.text||'',done:!!t.done,created:t.created||Date.now(),priority:t.priority||'medium',category:t.category||'Coding',due:t.due||''}));
  save(KEY.tasks,tasks);
  const input=taskInput.cloneNode(true), add=oldAdd.cloneNode(true), list=oldList.cloneNode(false), clear=oldClear.cloneNode(true);
  taskInput.replaceWith(input);oldAdd.replaceWith(add);oldList.replaceWith(list);oldClear.replaceWith(clear);
  input.id='taskInput';add.id='addTask';list.id='taskList';clear.id='clearDone';
  const card=document.querySelector('.tasks-card');
  const tools=document.createElement('div');tools.className='quest-tools';tools.innerHTML=`<div class="quest-options"><select id="taskPriority" aria-label="Priority"><option value="high">🔴 High</option><option value="medium" selected>🟡 Medium</option><option value="low">🟢 Low</option></select><select id="taskCategory" aria-label="Category"><option>Coding</option><option>DSA</option><option>Analytics</option><option>Interview</option><option>Personal</option></select><input id="taskDue" type="date" aria-label="Due date"></div><div class="quest-toolbar"><div class="task-filters"><button class="filter active" data-filter="all">All</button><button class="filter" data-filter="open">Open</button><button class="filter" data-filter="done">Done</button><button class="filter" data-filter="overdue">Overdue</button></div><input id="taskSearch" placeholder="⌕ Filter quests..." aria-label="Search quests"><span id="taskProgress">0 / 0</span></div>`;
  input.parentElement.after(tools);
  const progress=document.createElement('div');progress.className='quest-progress';progress.innerHTML='<i id="questProgressBar"></i>';tools.after(progress);
  const focus=document.createElement('button');focus.className='focus-btn';focus.id='focusBtn';focus.textContent='◷ Focus 25:00';card.querySelector('.card-heading').appendChild(focus);
  const style=document.createElement('style');style.textContent=`
    .tasks-card{height:330px!important}.quest-tools{position:relative;z-index:5;margin:7px 19px 5px}.quest-options{display:flex;gap:6px}.quest-options select,.quest-options input,.quest-toolbar input{height:27px;border:1px solid #28435f;border-radius:7px;background:#08182d;color:#9eb1c8;padding:0 7px;font-size:8px;outline:none}.quest-options select{flex:1;min-width:0}.quest-options input{width:105px;color:#8ea5c4}.quest-toolbar{display:flex;align-items:center;gap:6px;margin-top:6px}.task-filters{display:flex;gap:3px}.filter{border:1px solid #233d59;border-radius:6px;background:#08172c;color:#6f87a4;padding:4px 6px;font-size:7px;cursor:pointer}.filter.active,.filter:hover{border-color:#7d6b16;color:var(--yellow);background:rgba(255,210,31,.07)}#taskSearch{width:100px;margin-left:auto}.quest-toolbar>span{font-size:7px;color:#748ca8;white-space:nowrap}.quest-progress{height:3px;background:#1a304a;margin:2px 19px 6px;border-radius:9px;overflow:hidden;position:relative;z-index:5}.quest-progress i{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--green),var(--yellow));transition:.35s}.task-list{max-height:122px!important}.task{min-height:40px!important;padding:4px 8px!important}.task-main{min-width:0;flex:1}.task-main strong{display:block;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.task-main small{display:flex;gap:5px;color:#667f9c;font-size:7px;margin-top:2px}.task-badge{padding:2px 4px;border-radius:4px;background:#132640}.priority-high{color:#ff7180}.priority-medium{color:#ffd21f}.priority-low{color:#56e58a}.due-over{color:#ff6678!important}.due-today{color:#ffd21f!important}.task-actions{display:flex;gap:2px}.task-actions button{border:0;background:transparent;color:#607997;cursor:pointer;font-size:12px;padding:3px}.task-actions button:hover{color:#fff}.focus-btn{margin-left:auto;border:1px solid #2c4967;border-radius:8px;background:#09182d;color:#8fa6c2;padding:6px 8px;font-size:8px;cursor:pointer}.focus-btn:hover{color:var(--yellow);border-color:#8a7414}.empty-state{margin-top:4px!important}
    .focus-panel{text-align:center}.focus-time{font:800 56px 'Space Grotesk';letter-spacing:-2px;color:var(--yellow);margin:12px 0}.focus-ring{width:160px;height:160px;border-radius:50%;margin:0 auto 18px;display:grid;place-items:center;background:conic-gradient(var(--yellow) 0 100%,#1b304a 0);position:relative}.focus-ring:after{content:'';position:absolute;inset:10px;border-radius:50%;background:#07162b}.focus-ring .focus-time{position:relative;z-index:2;margin:0;font-size:34px}.focus-actions{display:flex;justify-content:center;gap:8px}.focus-actions button{border:1px solid #304c69;border-radius:8px;background:#09182d;color:#9eb0c5;padding:8px 12px;font-size:9px;cursor:pointer}.focus-actions .primary{background:linear-gradient(#ffdc38,#ffc000);color:#101827;border-color:#ffc000;font-weight:800}
  `;document.head.appendChild(style);
  let currentFilter='all',search='';
  function normalizeDue(d){return d||''}
  function isOverdue(t){return !t.done&&t.due&&t.due<dayKey()}
  function dueLabel(t){if(!t.due)return 'No deadline';const today=dayKey(),tom=new Date();tom.setDate(tom.getDate()+1);const td=tom.toISOString().slice(0,10);if(t.due<today)return 'Overdue';if(t.due===today)return 'Due today';if(t.due===td)return 'Due tomorrow';return new Date(t.due+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}
  function visible(){return tasks.filter(t=>{const match=!search||t.text.toLowerCase().includes(search)||t.category.toLowerCase().includes(search);const f=currentFilter==='all'||(currentFilter==='open'&&!t.done)||(currentFilter==='done'&&t.done)||(currentFilter==='overdue'&&isOverdue(t));return match&&f}).sort((a,b)=>(a.done-b.done)||(a.due||'9999').localeCompare(b.due||'9999'))}
  function render(){list.innerHTML='';const arr=visible();arr.forEach(t=>{const el=document.createElement('div');el.className='task'+(t.done?' completed':'');el.dataset.id=t.id;el.innerHTML=`<input type="checkbox" ${t.done?'checked':''} aria-label="Complete quest"><div class="task-main"><strong>${esc(t.text)}</strong><small><span class="task-badge">${esc(t.category)}</span><span class="${'priority-'+t.priority}">${t.priority.toUpperCase()}</span><span class="${isOverdue(t)?'due-over':t.due===dayKey()?'due-today':''}">• ${esc(dueLabel(t))}</span></small></div><div class="task-actions"><button data-action="edit" title="Edit">✎</button><button data-action="duplicate" title="Duplicate">⧉</button><button data-action="delete" title="Delete">×</button></div>`;list.appendChild(el)});$('#taskEmpty').style.display=arr.length?'none':'block';const done=tasks.filter(t=>t.done).length,total=tasks.length;$('#taskProgress').textContent=`${done} / ${total} done`;$('#questProgressBar').style.width=total?`${done/total*100}%`:'0%';updateStats()}
  function add(){const text=input.value.trim();if(!text)return;const t={id:`q_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,text,done:false,created:Date.now(),priority:$('#taskPriority').value,category:$('#taskCategory').value,due:$('#taskDue').value};tasks.unshift(t);save(KEY.tasks,tasks);input.value='';$('#taskDue').value='';render();toast(`${t.priority==='high'?'🔴 ':''}Quest added · ${t.category} · +10 XP ⚡`);input.focus()}
  add.onclick=add;input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();add()}});clear.onclick=()=>{const n=tasks.filter(t=>t.done).length;tasks=tasks.filter(t=>!t.done);save(KEY.tasks,tasks);render();toast(n?`${n} completed quest${n===1?'':'s'} cleared`:'No completed quests to clear')};
  list.addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;const t=tasks.find(x=>x.id===e.target.closest('.task').dataset.id);if(!t)return;t.done=e.target.checked;if(t.done){const k=dayKey();activity[k]=(activity[k]||0)+1;save(KEY.activity,activity);toast('Quest completed · +10 XP 🎉')}save(KEY.tasks,tasks);render();renderHeatmap()});
  list.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const el=b.closest('.task'),t=tasks.find(x=>x.id===el.dataset.id);if(!t)return;const a=b.dataset.action;if(a==='delete'){tasks=tasks.filter(x=>x.id!==t.id);save(KEY.tasks,tasks);render();toast('Quest deleted')}if(a==='duplicate'){tasks.unshift({...t,id:`q_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,done:false,created:Date.now()});save(KEY.tasks,tasks);render();toast('Quest duplicated')}if(a==='edit'){openEdit(t)}});
  function openEdit(t){openModal(`<div class="modal-title">✎ Edit Quest</div><div class="modal-sub">Update your quest without losing its progress.</div><div class="edit-form"><label>Quest name<input id="editText" value="${esc(t.text)}" maxlength="100"></label><label>Priority<select id="editPriority"><option value="high" ${t.priority==='high'?'selected':''}>🔴 High</option><option value="medium" ${t.priority==='medium'?'selected':''}>🟡 Medium</option><option value="low" ${t.priority==='low'?'selected':''}>🟢 Low</option></select></label><label>Category<select id="editCategory">${['Coding','DSA','Analytics','Interview','Personal'].map(x=>`<option ${x===t.category?'selected':''}>${x}</option>`).join('')}</select></label><label>Deadline<input id="editDue" type="date" value="${t.due||''}"></label><button class="save-edit" id="saveEdit">Save changes</button></div>`);$('#saveEdit').onclick=()=>{const text=$('#editText').value.trim();if(!text)return;Object.assign(t,{text,priority:$('#editPriority').value,category:$('#editCategory').value,due:$('#editDue').value});save(KEY.tasks,tasks);closeModal();render();toast('Quest updated ✨')}}
  $$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});$('#taskSearch').addEventListener('input',e=>{search=e.target.value.toLowerCase().trim();render()});
  function focusTimer(){openModal(`<div class="focus-panel"><div class="modal-title">◷ Focus Mode</div><div class="modal-sub">25 minutes of distraction-free coding.</div><div class="focus-ring"><div class="focus-time" id="focusTime">25:00</div></div><div class="focus-actions"><button class="primary" id="focusStart">Start Focus</button><button id="focusReset">Reset</button></div><p style="color:#617b99;font-size:9px;margin-top:15px">When the timer ends, complete a quest to keep your streak alive.</p></div>`);let sec=1500,timer=null;const out=$('#focusTime');function tick(){sec=Math.max(0,sec-1);out.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec===0){clearInterval(timer);toast('Focus session complete · +20 XP ⚡')}}$('#focusStart').onclick=()=>{if(timer)return;$('#focusStart').textContent='Running...';timer=setInterval(tick,1000)};$('#focusReset').onclick=()=>{clearInterval(timer);timer=null;sec=1500;out.textContent='25:00';$('#focusStart').textContent='Start Focus'}}
  $('#focusBtn').onclick=focusTimer;
  document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();input.focus()}if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#taskSearch').focus()}});
  window.addEventListener('storage',e=>{if(e.key===KEY.tasks){tasks=JSON.parse(e.newValue||'[]');render()}});
  render();
})();