(() => {
  'use strict';
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const KEY = { tasks: 'devboard.tasks.v2', notes: 'devboard.notes.v2', activity: 'devboard.activity.v2', theme: 'devboard.theme', muted: 'devboard.muted' };
  const read = (key, fallback) => { try { const v = localStorage.getItem(key); return v ? JSON.parse(v) : fallback; } catch { return fallback; } };
  const save = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const escape = value => { const d = document.createElement('div'); d.textContent = value ?? ''; return d.innerHTML; };
  let tasks = Array.isArray(read(KEY.tasks, [])) ? read(KEY.tasks, []) : [];
  let activity = read(KEY.activity, {}); if (!activity || typeof activity !== 'object') activity = {};
  let muted = localStorage.getItem(KEY.muted) === 'true';

  const today = () => new Date().toISOString().slice(0, 10);
  const normalize = (t, i) => ({ id: t.id || `q_${t.created || Date.now()}_${i}`, text: String(t.text || '').trim(), done: !!t.done, created: t.created || Date.now(), priority: ['high','medium','low'].includes(t.priority) ? t.priority : 'medium', category: t.category || 'Coding', due: t.due || '' });
  tasks = tasks.map(normalize).filter(t => t.text); save(KEY.tasks, tasks);

  function toast(message) { const el = $('#toast'); if (!el) return; el.textContent = message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast = setTimeout(() => el.classList.remove('show'), 2200); }
  function streak() { let n = 0, d = new Date(); while (activity[todayKey(d)] > 0) { n++; d.setDate(d.getDate() - 1); } return n; }
  function todayKey(d) { return d.toISOString().slice(0,10); }
  function dueStatus(t) { if (!t.due) return ['No deadline','']; if (t.done) return [new Date(t.due + 'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}),'']; const k=today(), tomorrow=new Date(); tomorrow.setDate(tomorrow.getDate()+1); const tk=tomorrow.toISOString().slice(0,10); if(t.due<k)return ['Overdue','due-over']; if(t.due===k)return ['Due today','due-today']; if(t.due===tk)return ['Due tomorrow','due-today']; return [new Date(t.due+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}),'']; }

  function updateStats() {
    const total=tasks.length, done=tasks.filter(t=>t.done).length, rate=total?Math.round(done/total*100):0, s=streak();
    [['#totalTasks',total],['#completedTasks',done],['#completionRate',rate+'%'],['#streak',s],['#heroStreak',`${s} day${s===1?'':'s'}`]].forEach(([sel,val])=>{const e=$(sel);if(e)e.textContent=val;});
    const xp=Math.min(500,260+done*10), pct=Math.round(xp/500*100);
    [['#xpValue',xp],['#heroXp',xp],['#xpPercent',pct+'%'],['#powerPercent',pct+'%']].forEach(([sel,val])=>{const e=$(sel);if(e)e.textContent=val;});
    ['#trainerProgress','#heroProgress'].forEach(sel=>{const e=$(sel);if(e)e.style.width=pct+'%';});
    const ring=$('#powerRing'); if(ring) ring.style.background=`conic-gradient(var(--yellow) 0 ${pct}%, #1a304b ${pct}% 100%)`;
    const level=$('#powerLevel'); if(level) level.textContent=pct>=90?'Elite Trainer':pct>=70?'Advanced Trainer':pct>=50?'Rising Trainer':'New Trainer';
    const milestone=done===0?['First Quest','Complete a task to unlock your first badge.']:done<5?['Quest Hunter',`${5-done} more completed quest${5-done===1?'':'s'} to unlock.`]:done<10?['Combo Master',`${10-done} more completed quest${10-done===1?'':'s'} to unlock.`]:['Evolution Ready','You have completed 10+ quests. Keep going!'];
    if($('#milestoneText'))$('#milestoneText').textContent=milestone[0]; if($('#milestoneSub'))$('#milestoneSub').textContent=milestone[1];
    const vals=Object.values(activity).map(Number).filter(Number.isFinite), totalActivity=vals.reduce((a,b)=>a+b,0), active=vals.filter(v=>v>0).length;
    if($('#activityTotal'))$('#activityTotal').textContent=totalActivity; if($('#activityBest'))$('#activityBest').textContent=`Best: ${vals.length?Math.max(...vals):0}/day`; if($('#activeDays'))$('#activeDays').textContent=`${active} active day${active===1?'':'s'}`;
  }

  let filter='all', search='';
  function visibleTasks(){ return tasks.filter(t => { const q=!search || t.text.toLowerCase().includes(search) || t.category.toLowerCase().includes(search); const ok=filter==='all'||(filter==='open'&&!t.done)||(filter==='done'&&t.done)||(filter==='overdue'&&!t.done&&t.due&&t.due<today()); return q&&ok; }).sort((a,b)=>(a.done-b.done)||(a.due||'9999').localeCompare(b.due||'9999')); }
  function renderTasks(){ const list=$('#taskList'); if(!list)return; list.innerHTML=''; const arr=visibleTasks(); arr.forEach(t=>{ const row=document.createElement('div'); row.className='task'+(t.done?' completed':''); row.dataset.id=t.id; const [due,cls]=dueStatus(t); row.innerHTML=`<input type="checkbox" ${t.done?'checked':''} aria-label="Complete quest"><div class="task-main"><strong>${escape(t.text)}</strong><small><span class="task-badge">${escape(t.category)}</span><span class="priority-${t.priority}">${t.priority.toUpperCase()}</span><span class="${cls}">• ${escape(due)}</span></small></div><div class="task-actions"><button data-action="edit" title="Edit">✎</button><button data-action="duplicate" title="Duplicate">⧉</button><button data-action="delete" title="Delete">×</button></div>`; list.appendChild(row); }); const empty=$('#taskEmpty'); if(empty)empty.style.display=arr.length?'none':'block'; const done=tasks.filter(t=>t.done).length; if($('#taskProgress'))$('#taskProgress').textContent=`${done} / ${tasks.length} done`; if($('#questProgressBar'))$('#questProgressBar').style.width=tasks.length?`${done/tasks.length*100}%`:'0%'; updateStats(); }

  function addTask(){const input=$('#taskInput'); if(!input)return; const text=input.value.trim(); if(!text){input.focus();return;} const t={id:`q_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,text,done:false,created:Date.now(),priority:$('#taskPriority')?.value||'medium',category:$('#taskCategory')?.value||'Coding',due:$('#taskDue')?.value||''}; tasks.unshift(t);save(KEY.tasks,tasks);input.value='';if($('#taskDue'))$('#taskDue').value='';renderTasks();toast('Quest added · +10 XP ⚡');input.focus();}

  function renderHeatmap(){const h=$('#heatmap');if(!h)return;h.innerHTML='';for(let i=83;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=todayKey(d),v=Number(activity[k]||0),c=document.createElement('div');c.className='heatmap-cell '+(v>=4?'level4':v===3?'level3':v===2?'level2':v===1?'level1':'');c.title=`${v} completed quest${v===1?'':'s'} · ${k}`;h.appendChild(c);}}

  function openModal(html){const m=$('#modal'),c=$('#modalContent');if(!m||!c)return;c.innerHTML=html;m.classList.add('open');m.setAttribute('aria-hidden','false');}
  function closeModal(){const m=$('#modal');if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');}}
  function editTask(t){openModal(`<div class="modal-title">✎ Edit Quest</div><div class="modal-sub">Update your quest details.</div><div class="edit-form"><label>Quest name<input id="editText" value="${escape(t.text)}" maxlength="100"></label><label>Priority<select id="editPriority"><option value="high" ${t.priority==='high'?'selected':''}>🔴 High</option><option value="medium" ${t.priority==='medium'?'selected':''}>🟡 Medium</option><option value="low" ${t.priority==='low'?'selected':''}>🟢 Low</option></select></label><label>Category<select id="editCategory">${['Coding','DSA','Analytics','Interview','Personal'].map(x=>`<option ${x===t.category?'selected':''}>${x}</option>`).join('')}</select></label><label>Deadline<input id="editDue" type="date" value="${t.due}"></label><button class="save-edit" id="saveEdit">Save changes</button></div>`);$('#saveEdit').onclick=()=>{const text=$('#editText').value.trim();if(!text)return;Object.assign(t,{text,priority:$('#editPriority').value,category:$('#editCategory').value,due:$('#editDue').value});save(KEY.tasks,tasks);closeModal();renderTasks();toast('Quest updated ✨');};}
  function achievements(){const done=tasks.filter(t=>t.done).length,s=streak(),active=Object.values(activity).filter(v=>v>0).length,items=[['⚡','First Quest','Complete your first quest',done>=1],['🎯','Quest Hunter','Complete 5 quests',done>=5],['🔥','On Fire','Reach a 7 day streak',s>=7],['💻','Code Trainer','Complete 10 quests',done>=10],['🏆','Evolution','Reach 25 completed quests',done>=25],['✦','Legend','Reach 30 active days',active>=30]];openModal(`<div class="modal-title">🏆 Achievements</div><div class="modal-sub">Your badges evolve as you use DevBoard.</div><div class="achievement-grid">${items.map(x=>`<div class="achievement ${x[3]?'':'locked'}"><b>${x[0]} ${x[1]}</b><span>${x[2]}</span><small>${x[3]?'UNLOCKED':'LOCKED'}</small></div>`).join('')}</div>`);}
  function settings(){openModal(`<div class="modal-title">⚙ Settings</div><div class="modal-sub">Your data stays in this browser.</div><div class="settings-grid"><div class="setting-row"><div><strong>Appearance</strong><span>Toggle light/dark mode.</span></div><button class="outline-btn" id="settingsTheme">Toggle</button></div><div class="setting-row"><div><strong>Sound</strong><span>Toggle dashboard feedback.</span></div><button class="outline-btn" id="settingsMute">Toggle</button></div><div class="setting-row"><div><strong>Clear completed</strong><span>Remove finished quests.</span></div><button class="outline-btn" id="settingsClear">Clear</button></div><div class="setting-row"><div><strong>Reset dashboard</strong><span>Delete all local tasks, notes and activity.</span></div><button class="outline-btn" id="settingsReset">Reset</button></div></div>`);$('#settingsTheme').onclick=()=>{$('#themeBtn')?.click();settings();};$('#settingsMute').onclick=()=>{$('#muteBtn')?.click();settings();};$('#settingsClear').onclick=()=>{tasks=tasks.filter(t=>!t.done);save(KEY.tasks,tasks);renderTasks();settings();};$('#settingsReset').onclick=()=>{if(confirm('Reset all local DevBoard data?')){tasks=[];activity={};localStorage.removeItem(KEY.tasks);localStorage.removeItem(KEY.notes);localStorage.removeItem(KEY.activity);if($('#notes'))$('#notes').value='';renderTasks();renderHeatmap();updateStats();settings();toast('Dashboard reset');}};}

  function navigate(section){$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===section));const names={dashboard:'Dashboard',tasks:'Tasks',notes:'Notes',activity:'Activity',projects:'Projects',achievements:'Achievements',settings:'Settings'};if($('#pageName'))$('#pageName').textContent=names[section]||'Dashboard';if(section==='achievements')return achievements();if(section==='settings')return settings();const target=$(`[data-section-panel="${section}"]`);if(target)target.scrollIntoView({behavior:'smooth',block:'center'});if(section==='tasks')setTimeout(()=>$('#taskInput')?.focus(),350);}

  function focusMode(){openModal(`<div class="focus-panel"><div class="modal-title">◷ Focus Mode</div><div class="modal-sub">25 minutes of distraction-free coding.</div><div class="focus-ring"><div class="focus-time" id="focusTime">25:00</div></div><div class="focus-actions"><button class="primary" id="focusStart">Start Focus</button><button id="focusReset">Reset</button></div></div>`);let seconds=1500,timer=null;const out=$('#focusTime');const draw=()=>{out.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;};$('#focusStart').onclick=()=>{if(timer)return;$('#focusStart').textContent='Running...';timer=setInterval(()=>{seconds--;draw();if(seconds<=0){clearInterval(timer);timer=null;toast('Focus session complete · +20 XP ⚡');$('#focusStart').textContent='Complete';}},1000);};$('#focusReset').onclick=()=>{clearInterval(timer);timer=null;seconds=1500;draw();$('#focusStart').textContent='Start Focus';};}

  function init(){
    const date=$('#currentDate'), tz=$('#timezone'), year=$('#footerYear'); const tickDate=()=>{const d=new Date();if(date)date.textContent=d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});if(tz)tz.textContent=Intl.DateTimeFormat().resolvedOptions().timeZone.replace('_',' ');if(year)year.textContent=d.getFullYear();}; const tickClock=()=>{const e=$('#clock');if(!e)return;const d=new Date();e.textContent=d.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit'});}; tickDate();tickClock();setInterval(tickClock,1000);setInterval(tickDate,60000);
    const notes=$('#notes');if(notes){notes.value=localStorage.getItem(KEY.notes)||'';const words=()=>{if($('#wordCount'))$('#wordCount').textContent=(notes.value.trim()?notes.value.trim().split(/\s+/).length:0)+' words';};words();notes.addEventListener('input',()=>{localStorage.setItem(KEY.notes,notes.value);if($('#saveStatus'))$('#saveStatus').textContent='● Saving...';clearTimeout(window.__save);window.__save=setTimeout(()=>{if($('#saveStatus'))$('#saveStatus').textContent='● Saved';},450);words();});}
    const light=localStorage.getItem(KEY.theme)==='light';document.body.classList.toggle('light',light);if($('#themeBtn'))$('#themeBtn').textContent=light?'🌙':'☀️';if($('#themeBtn'))$('#themeBtn').onclick=()=>{const on=!document.body.classList.contains('light');document.body.classList.toggle('light',on);localStorage.setItem(KEY.theme,on?'light':'dark');$('#themeBtn').textContent=on?'🌙':'☀️';toast(on?'Light mode enabled':'Dark mode enabled');};
    const setMute=()=>{if($('#muteBtn'))$('#muteBtn').textContent=muted?'🔇':'🔊';};setMute();if($('#muteBtn'))$('#muteBtn').onclick=()=>{muted=!muted;localStorage.setItem(KEY.muted,muted);setMute();toast(muted?'Sound muted':'Sound enabled');};
    $('#addTask')?.addEventListener('click',addTask);$('#taskInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addTask();}});
    $('#taskList')?.addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;const row=e.target.closest('.task'),t=tasks.find(x=>x.id===row?.dataset.id);if(!t)return;t.done=e.target.checked;if(t.done){const k=today();activity[k]=(activity[k]||0)+1;save(KEY.activity,activity);toast('Quest completed · +10 XP 🎉');}save(KEY.tasks,tasks);renderTasks();renderHeatmap();});
    $('#taskList')?.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const row=b.closest('.task'),t=tasks.find(x=>x.id===row?.dataset.id);if(!t)return;if(b.dataset.action==='delete'){tasks=tasks.filter(x=>x.id!==t.id);save(KEY.tasks,tasks);renderTasks();toast('Quest deleted');}else if(b.dataset.action==='duplicate'){tasks.unshift({...t,id:`q_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,done:false,created:Date.now()});save(KEY.tasks,tasks);renderTasks();toast('Quest duplicated');}else editTask(t);});
    $('#clearDone')?.addEventListener('click',()=>{tasks=tasks.filter(t=>!t.done);save(KEY.tasks,tasks);renderTasks();toast('Completed quests cleared');});
    $$('.nav-item').forEach(b=>b.addEventListener('click',()=>{navigate(b.dataset.section);$('#sidebar')?.classList.remove('open');}));$('#profileBtn')?.addEventListener('click',()=>openModal(`<div class="profile-modal"><div class="profile-big">NK</div><div class="modal-title">Code Trainer</div><div class="modal-sub">Level 5 · Pokémon Developer</div><div class="setting-row"><div><strong>Quest completion</strong><span>${tasks.filter(t=>t.done).length} completed out of ${tasks.length}</span></div><strong style="color:var(--yellow)">${tasks.length?Math.round(tasks.filter(t=>t.done).length/tasks.length*100):0}%</strong></div></div>`));
    $('#shareBtn')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:'DevBoard ⚡',text:'Check out my Pokémon developer dashboard!'});else{await navigator.clipboard.writeText(location.href);toast('Dashboard link copied');}}catch{}});
    $('#mobileMenu')?.addEventListener('click',()=>$('#sidebar')?.classList.toggle('open'));$('#addProject')?.addEventListener('click',()=>openModal('<div class="modal-title">✨ New Project</div><div class="modal-sub">Add your next project to the Pokédex.</div><div class="setting-row"><strong>Project manager ready</strong><span>Add a real URL when your project is published.</span></div>'));$$('.project-link').forEach(b=>b.addEventListener('click',()=>{const p=b.closest('.project');openModal(`<div class="modal-title">${escape(p.dataset.project||'Project')}</div><div class="modal-sub">Pokédex project profile</div><div class="setting-row"><strong>Stack</strong><span>${$$('.tags span',p).map(x=>x.textContent).join(' · ')}</span></div>`);}));
    $('#focusBtn')?.addEventListener('click',focusMode);$$('[data-open="achievements"]').forEach(b=>b.addEventListener('click',achievements));$('#modal')?.addEventListener('click',e=>{if(e.target.hasAttribute('data-close'))closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openModal('<div class="modal-title">⌕ Quick Navigation</div><div class="command-grid">'+['dashboard','tasks','notes','activity','projects','achievements','settings'].map(x=>`<button class="outline-btn" data-nav="${x}">${x}</button>`).join('')+'</div>');$$('[data-nav]').forEach(b=>b.onclick=()=>{closeModal();navigate(b.dataset.nav);});}if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))$('#taskInput')?.focus();if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#taskSearch')?.focus();}});
    const tools=document.createElement('div');tools.className='quest-tools';tools.innerHTML='<div class="quest-options"><select id="taskPriority"><option value="high">🔴 High</option><option value="medium" selected>🟡 Medium</option><option value="low">🟢 Low</option></select><select id="taskCategory"><option>Coding</option><option>DSA</option><option>Analytics</option><option>Interview</option><option>Personal</option></select><input id="taskDue" type="date"></div><div class="quest-toolbar"><div class="task-filters"><button class="filter active" data-filter="all">All</button><button class="filter" data-filter="open">Open</button><button class="filter" data-filter="done">Done</button><button class="filter" data-filter="overdue">Overdue</button></div><input id="taskSearch" placeholder="⌕ Filter quests..."><span id="taskProgress">0 / 0</span></div>';$('#taskInput')?.parentElement.after(tools);const progress=document.createElement('div');progress.className='quest-progress';progress.innerHTML='<i id="questProgressBar"></i>';tools.after(progress);$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderTasks();}));$('#taskSearch')?.addEventListener('input',e=>{search=e.target.value.toLowerCase().trim();renderTasks();});
    renderTasks();renderHeatmap();updateStats();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
